// ═══════════════════════════════════════════════════════
//  CleanOps Academy — Items Data
//  src/game/data/items.ts
// ═══════════════════════════════════════════════════════

import type { GameItem } from '../types';

export const WINDOW_ITEMS: GameItem[] = [
  {
    id: 'glass_cleaner',
    name: 'Glass Cleaner',
    category: 'Product',
    icon: '🧴',
    color: 0x2255cc,
    desc: 'Used for cleaning glass and mirrors. Leaves a streak-free shine.',
    correctForMission: true,
    shape: 'bottle',
    pos: [-3, 0.5, 1.5],
    scale: [0.18, 0.35, 0.12],
  },
  {
    id: 'microfiber_cloth',
    name: 'Microfiber Cloth',
    category: 'Tool',
    icon: '🧹',
    color: 0x44aaee,
    desc: 'Soft cloth used to clean glass without scratching. Absorbs cleaning product effectively.',
    correctForMission: true,
    shape: 'cloth',
    pos: [-3, 0.5, 0.5],
    scale: [0.22, 0.08, 0.28],
  },
  {
    id: 'mop',
    name: 'Mop',
    category: 'Tool',
    icon: '🧹',
    color: 0x888855,
    desc: 'Used for cleaning floors. Not suitable for window cleaning.',
    correctForMission: false,
    shape: 'mop',
    pos: [2.5, 0.9, -1],
    scale: [0.1, 1.0, 0.1],
  },
  {
    id: 'garbage_bag',
    name: 'Garbage Bag',
    category: 'Supply',
    icon: '🗑',
    color: 0x222222,
    desc: 'Used for collecting and removing garbage. Not for cleaning windows.',
    correctForMission: false,
    shape: 'bag',
    pos: [2, 0.3, 1.5],
    scale: [0.25, 0.4, 0.2],
  },
  {
    id: 'floor_cleaner',
    name: 'Floor Cleaner',
    category: 'Product',
    icon: '🧴',
    color: 0xcc7722,
    desc: 'Used for floor cleaning. Not effective or appropriate for glass surfaces.',
    correctForMission: false,
    shape: 'bottle',
    pos: [-3, 0.5, -0.5],
    scale: [0.18, 0.38, 0.14],
  },
  {
    id: 'disinfectant',
    name: 'Disinfectant Spray',
    category: 'Product',
    icon: '🧴',
    color: 0x22aa66,
    desc: 'Used to disinfect high-touch surfaces. It is not the best product for cleaning windows.',
    correctForMission: false,
    shape: 'bottle',
    pos: [-3, 0.5, -1.5],
    scale: [0.16, 0.30, 0.12],
  },
  {
    id: 'paper_towel',
    name: 'Paper Towel Roll',
    category: 'Supply',
    icon: '🧻',
    color: 0xddddcc,
    desc: 'Can wipe spills, but a microfiber cloth is preferred for window cleaning.',
    correctForMission: false,
    shape: 'roll',
    pos: [0, 0.55, -3.2],
    scale: [0.15, 0.25, 0.15],
  },
];
